                  id                  |       name       | category  | cook_time |                               ingredients                                |                                                                      recipe                                                                      | photo_url 
--------------------------------------+------------------+-----------+-----------+--------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+-----------
 6fbc642d-1693-4ac7-a4fc-e91582a85de6 | Carbonara        | Main      | 30 min    | Eggs, parmesan cheese, pasta, pepper, salt                               | Sauté guanciale until golden. Mix hot cooked pasta vigorously with the guanciale, egg, cheese and a splash of pasta cooking water and watch...   | 
 715d23f3-203c-400e-a55b-eefa7aa36090 | Margherita Pizza | Main      | 25 min    | Flour, yeast, water, salt, tomato, mozzarella, basil, olive oil          | Prepare pizza dough and let it rise. Spread tomato sauce, add mozzarella, and bake at high temperature until crust is golden and cheese melts... | 
 79ec7c78-6f18-4e0c-a802-d743f0abedb4 | Caesar Salad     | Appetizer | 15 min    | Romaine lettuce, croutons, parmesan cheese, Caesar dressing              | Chop lettuce, toss with croutons and Caesar dressing. Sprinkle with grated parmesan and serve chilled.                                           | 
 d0df51c7-cb3e-435c-84c5-4ac160404016 | Chicken Curry    | Main      | 45 min    | Chicken, curry powder, coconut milk, onion, garlic, ginger, salt, pepper | Sauté onions, garlic, and ginger. Add chicken and curry powder. Pour in coconut milk, simmer until chicken is tender.                            | 
 c4e9b322-3312-4306-8339-6e086370ecc4 | Chocolate Cake   | Dessert   | 60 min    | Flour, cocoa powder, sugar, eggs, butter, milk, baking powder            | Mix dry and wet ingredients separately. Combine and bake at 350°F (175°C) for 40 minutes until a toothpick comes out clean.                      | 
(5 rows)

